#include <iostream>

int main(){
  cout << "

TODAY it seems to me providential that Fate should have chosen Braunau on the Inn as my birthplace. For this little town lies on the boundary between two German states which we of the younger generation at least have made it our life work to reunite by every means at our disposal.

German-Austria must return to the great German mother country, and not because of any economic considerations. No, and again no: even if such a union were unimportant from an economic point of view; yes, even if it were harmful, it must nevertheless take place. One blood demands one Reich. Never will the German nation possess the moral right to engage in colonial politics until, at least, it embraces its own sons within a single state. Only when the Reich borders include the very last German, but can no longer guarantee his daily bread, will the moral right to acquire foreign soil arise from the distress of our own people. Their sword will become our plow, and from the tears of war the daily bread of future generations will grow. And so this little city on the border seems to me the symbol of a great mission. And in another respect as well, it looms as an admonition to the present day. More than a hundred years ago, this insignificant place had the distinction of being immortalized in the annals at least of German history, for it was the scene of a tragic catastrophe which gripped the entire German nation. At the time of our fatherland's deepest humiliation, Johannes Palm of Nuremberg, burgher, bookseller, uncompromising nationalist and French hater, died there for the Germany which he loved so passionately even in her misfortune. He had stubbornly refused to denounce his accomplices who were in fact his superiors. In thus he resembled Leo Schlageter. And like him, he was denounced to the French by a representative of his government An Augsburg police chief won this unenviable fame, thus furnishing an example for our modern German officials in Herr Severing's Reich.

In this little town on the Inn, gilded by the rays of German martyrdom, Bavarian by blood, technically Austrian, lived my parents in the late eighties of the past century; my father a dutiful civil servants my mother giving all her being to the household, and devoted above all to us children in eternal, loving care Little remains in my memory of this period, for after a few years my father had to leave the little border city he had learned to love, moving down the Inn to take a new position in Passau, that is, in Germany proper.

In those days constant moving was the lot of an Austrian customs official. A short time later, my father was sent to Linz, and there he was finally pensioned. Yet, indeed, this was not to mean 'rest' for the old gentleman. In his younger days, as the son of a poor cottager, he couldn't bear to stay at home. Before he was even thirteen, the little boy laced his tiny knapsack and ran away from his home in the Waldviertel. Despite the at tempts of 'experienced' villagers to dissuade him, he made his way to Vienna, there to learn a trade. This was in the fifties of the past century. A desperate decision, to take to the road with only three gulden for travel money, and plunge into the unknown. By the time the thirteen-year-old grew to be seventeen, he had passed his apprentice's examination, but he was not yet content. On the contrary. The long period of hardship, endless misery, and suffering he had gone through strengthened his determination to give up his trade and become 'something better.' Formerly the poor boy had regarded the priest as the embodiment of all humanly attainable heights; now in the big city, which had so greatly widened his perspective, it was the rank of civil servant. With all the tenacity of a young man whom suffering and care had made 'old' while still half a child, the seventeen-year-old clung to his new decision - he did enter the civil service. And after nearly twenty-three years, I believe, he reached his goal. Thus he seemed to have fulfilled a vow which he had made as a poor boy: that he would not return to his beloved native village until he had made something of himself.

His goal was achieved; but no one in the village could remember the little boy of former days, and to him the village had grown strange.

When finally, at the age of fifty-six, he went into retirement, he could not bear to spend a single day of his leisure in idleness. Near the Upper Austrian market village of Lambach he bought a farm, which he worked himself, and thus, in the circuit of a long and industrious life, returned to the origins of his forefathers.

It was at this time that the first ideals took shape in my breast. All my playing about in the open, the long walk to school, and particularly my association with extremely 'husky' boys, which sometimes caused my mother bitter anguish, made me the very opposite of a stay-at-home. And though at that time I scarcely had any serious ideas as to the profession I should one day pursue, my sympathies were in any case not in the direction of my father's career. I believe that even then my oratorical talent was being developed in the form of more or less violent arguments with my schoolmates. I had become a little ringleader; at school I learned easily and at that time very well, but was otherwise rather hard to handle. Since in my free time I received singing lessons in the cloister at Lambach, I had excellent opportunity to intoxicate myself with the solemn splendor of the brilliant church festivals. As was only natural the abbot seemed to me, as the village priest had once seemed to my father, the highest and most desirable ideal. For a time, at least, this was the case. But since my father, for understandable reasons, proved unable to appreciate the oratorical talents of his pugnacious boy, or to draw from them any favorable conclusions regarding the future of his offspring, he could, it goes without saying, achieve no understanding for such youthful ideas. With concern he observed this conflict of nature.

As it happened, my temporary aspiration for this profession was in any case soon to vanish, making place for hopes more stated to my temperament. Rummaging through my father's library, I had come across various books of a military nature among them a popular edition of the Franco-German War of 1870-71. It consisted of two issues of an illustrated periodical from those years, which now became my favorite reading matter It was not long before the great heroic struggle had become my greatest inner experience. From then on I became more and more enthusiastic about everything that was in any way connected with war or, for that matter, with soldiering

But in another respect as well, this was to assume importance for me. For the first time, though as yet in a confused form, the question was forced upon my consciousness: Was there a difference - and if so what difference - between the Germans who fought these battles and other Germans? Why hadn't Austria taken part in this war; why hadn't my father and all the others fought?

Are we not the same as all other Germans?

Do we not all belong together? This problem began to gnaw at my little brain for the first time. I asked cautious questions and with secret envy received the answer that not every German was fortunate enough to belong to Bismarck's Reich..

This was more than I could understand." << endl;


  return 0;
}
